---
- name: Update and upgrade the system packages
  hosts: all
  become: yes
  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    - name: Upgrade all packages (Debian-based)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_facts.os_family == "Debian"
