---
- name: Create and delete a user named user3
  hosts: all
  become: yes
  tasks:

    # Task to create the user
    - name: Create user user3
      user:
        name: user3
        state: present
        shell: /bin/bash
        comment: "User 3"
      tags:
        - create_user

    # Task to delete the user
    - name: Delete user user3
      user:
        name: user3
        state: absent
      tags:
        - delete_user



