---
- name: Install MariaDB, create database, user
  hosts: db
  become: true  
  gather_facts: yes

  tasks:
    - name: Install MariaDB server on Debian-based systems
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes
      when: ansible_facts['pkg_mgr'] == 'apt'

    - name: Start and enable MariaDB service
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Ensure MariaDB is running
      ansible.builtin.service:
        name: mariadb
        state: started

    - name: Create a new database
      community.mysql.mysql_db:
        name: my_database
        state: present

